[tool.poetry]
name = "pybirthday"
version = "0.1.0"
description = ""
authors = ["ZacKennedy-Smit <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
dearpygui = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
